-- Table: trips
create table if not exists trips (
  name text primary key,
  date text not null,
  channel_id text, -- Main channel for notifications (e.g. itinerary)
  dashboard_message_id text -- ID of the pinned dashboard message
);

-- Table: packing_items
create table if not exists packing_items (
  id bigint generated by default as identity primary key,
  trip_name text not null references trips(name) on delete cascade,
  item text not null,
  claimed_by text
);

-- Table: expenses
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  trip_name text not null references trips(name) on delete cascade,
  payer text not null,
  amount numeric not null,
  description text not null,
  date text not null
);

-- Table: user_settings (For Smart Context)
create table if not exists user_settings (
  user_id text primary key,
  active_trip text references trips(name) on delete set null
);

-- Table: itinerary (For Itinerary Intelligence)
create table if not exists itinerary (
  id bigint generated by default as identity primary key,
  trip_name text not null references trips(name) on delete cascade,
  title text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone,
  location text,
  notes text,
  assigned_to text
);

-- Table: reminders (For Reminder Engine)
create table if not exists reminders (
  id bigint generated by default as identity primary key,
  trip_name text not null references trips(name) on delete cascade,
  user_id text not null,
  channel_id text,
  message text not null,
  remind_at timestamp with time zone not null,
  created_at timestamp with time zone default now()
);

-- Table: polls (For Advanced Polling)
create table if not exists polls (
  id bigint generated by default as identity primary key,
  trip_name text references trips(name) on delete cascade,
  question text not null,
  options jsonb not null, -- Array of strings
  creator_id text not null,
  created_at timestamp with time zone default now(),
  expires_at timestamp with time zone,
  is_active boolean default true,
  message_id text, -- Discord message ID to update
  channel_id text -- Discord channel ID
);

-- Table: poll_votes (For Advanced Polling)
create table if not exists poll_votes (
  id bigint generated by default as identity primary key,
  poll_id bigint references polls(id) on delete cascade,
  user_id text not null,
  option_index integer not null,
  weight integer default 1,
  unique(poll_id, user_id)
);

-- Table: locations (For Location Intelligence)
create table if not exists locations (
  id bigint generated by default as identity primary key,
  trip_name text not null references trips(name) on delete cascade,
  name text not null,
  address text,
  url text, -- Google Maps Link
  type text not null, -- Hotel, Restaurant, Activity, Meetup
  added_by text
);

-- Table: checkins (For Location Intelligence)
create table if not exists checkins (
  id bigint generated by default as identity primary key,
  trip_name text not null references trips(name) on delete cascade,
  user_id text not null,
  user_name text not null, -- Cache display name
  location_id bigint references locations(id) on delete cascade,
  timestamp timestamp with time zone default now()
);

-- Table: memories (For Media Vault)
create table if not exists memories (
  id bigint generated by default as identity primary key,
  trip_name text not null references trips(name) on delete cascade,
  url text not null,
  caption text,
  day_number integer, -- Trip Day (1, 2, etc.)
  user_id text not null,
  created_at timestamp with time zone default now()
);

-- Table: server_modules (For Plugin Architecture)
create table if not exists server_modules (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  module_name text not null,
  is_enabled boolean default true,
  unique(guild_id, module_name)
);
