-- Create the feedback table
create table public.feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_name text not null,
  message text not null
);

-- Set up RLS (Row Level Security) if needed, but for now we'll leave it open for the service role key to write
alter table public.feedback enable row level security;

-- Allow insert for anyone (if using anon key) or just authenticated (if using service role in bot)
-- Since the bot uses the service role key (usually), it bypasses RLS, but good practice to define policies.
-- For now, we'll just create the table.
